export enum udResult {
  Success,
  Failure,
  NothingToDo,
  InternalError,
  NotInitialized,
  InvalidConfiguration,
  InvalidParameter,
  OutstandingReferences,
  MemoryAllocationFailure,
  CountExceeded,
  NotFound,
  BufferTooSmall,
  FormatVariationNotSupported,
  ObjectTypeMismatch,
  CorruptData,
  InputExhausted,
  OutputExhausted,
  CompressionError,
  Unsupported,
  Timeout,
  AlignmentRequired,
  DecryptionKeyRequired,
  DecryptionKeyMismatch,
  SignatureMismatch,
  ObjectExpired,
  ParseError,
  InternalCryptoError,
  OutOfOrder,
  OutOfRange,
  CalledMoreThanOnce,
  ImageLoadFailure,
  StreamerNotInitialised,

  OpenFailure,
  CloseFailure,
  ReadFailure,
  WriteFailure,
  SocketError,

  DatabaseError,
  ServerError,
  AuthError,
  NotAllowed,
  InvalidLicense,
  Pending,
  Cancelled,
  OutOfSync,
  SessionExpired,

  ProxyError,
  ProxyAuthRequired,
  ExceededAllowedLimit,

  RateLimited,
  PremiumOnly,
  InProgress
}
